---
title: "Reproducible workflows: Quarto, Git, GitHub"
subtitle: "rstudio::conf(2022) <br> Designing the data science classroom"
author: "Mine Çetinkaya-Rundel + Maria Tackett"
footer: "[🔗 rstd.io/teach-ds-conf22](https://rstd.io/teach-ds-conf22)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: ../slides.scss
    multiplex: true
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    center: true
execute:
  freeze: auto
---

```{r load-packages}
#| warning: false
#| message: false
library(ghclass)
library(countdown)
```

# Reproducibility in the classroom

## Reproducibility checklist

-   Are the tables and figures reproducible from the code and data?
-   Does the code actually do what you think it does?
-   In addition to what was done, is it clear *why* it was done? (e.g., how were parameter settings chosen?)
-   Can the code be used for other data?
-   Can you extend the code to do other things?

## Ambitious goal + many other concerns

We need an environment where

-   data, analysis, and results are tightly connected, or better yet, inseparable

-   reproducibility is built in

    -   the original data remains untouched
    -   all data manipulations and analyses are inherently documented

-   documentation is human readable and syntax is minimal

## Roadmap

-   Scriptability $\rightarrow$ R
-   Literate programming (code, narrative, output in one place) $\rightarrow$ Quarto
-   Version control $\rightarrow$ Git / GitHub

# Literate programming

## Why Quarto?

-   **Reproducibility:** Train new analysts whose only workflow is a reproducible one
-   **Pedagogy:**
    -   Code + output + prose together
    -   Syntax highlighting FTW!
    -   Familiar-feeling authoring with the visual editor without having to learn a bunch of new markdown syntax
-   **Efficiency:** Consistent formatting -\> easier grading
-   **Extendability:** Use with Python, and Julia, and Observable, and more

## Tips for starting with Quarto

-   Minimal YAML
-   Minimal chunk options
-   Use well scaffolded Quarto documents
-   Render early and often!

## Demo: Quarto 💙 visual editor

::: cloud
{{< fa cloud >}} RStudio Cloud > "Module 6 - Reproducibility" > ex-1-1.qmd
:::

-   Document YAML
-   Code chunks with YAML style options
-   YAML completion and diagnostics
-   Accessibility features
-   Citations
-   And more...

# 
